// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn8CUzAYzobdl7TW1h2c1VT6PMfvJ-awU',
    appId: '1:291630506544:web:5db882093e14c833d303f5',
    messagingSenderId: '291630506544',
    projectId: 'sportsapp-753c6',
    authDomain: 'sportsapp-753c6.firebaseapp.com',
    storageBucket: 'sportsapp-753c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRx_FcdXDcxJ7RL4ZYOL4V31LjpSxZYn4',
    appId: '1:291630506544:android:a59fee30c8001d3ed303f5',
    messagingSenderId: '291630506544',
    projectId: 'sportsapp-753c6',
    storageBucket: 'sportsapp-753c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGU6eg7cFmL476XKxpmY4v9APGUDJ7q6U',
    appId: '1:291630506544:ios:388b44e043ca1745d303f5',
    messagingSenderId: '291630506544',
    projectId: 'sportsapp-753c6',
    storageBucket: 'sportsapp-753c6.appspot.com',
    iosClientId: '291630506544-c5f6b4ofra64ar4k4njr525n25m211dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFiers',
  );
}
